apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "do-floating-ip-manager.fullname" . }}
  labels:
    {{- include "do-floating-ip-manager.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - {{ .Release.Name }}-cmips
    verbs:
      - get