apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "do-floating-ip-manager.fullname" . }}
  labels:
    {{- include "do-floating-ip-manager.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "do-floating-ip-manager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "do-floating-ip-manager.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "do-floating-ip-manager.serviceAccountName" . }}
      hostNetwork: true
      containers:
        - name: manager
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "NET_RAW"]
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          args: ["-v={{ .Values.verbosity }}", "-alsologtostderr", "-dry={{ .Values.dryRun }}"]
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: POD_NAMESPACE
            value: "{{ .Release.Namespace }}"
          - name: CONFIGMAP_NAME
            value: "{{ .Release.Name }}-cmips"
          - name: DO_TOKEN
            valueFrom:
              secretKeyRef:
                name: do-token
                key: token
          - name: HOSTNAME_FLOATING_IP_MATCH_STRING
            value: {{ .Values.matchString }}
