apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "do-floating-ip-manager.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "do-floating-ip-manager.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "do-floating-ip-manager.fullname" . }}
  apiGroup: rbac.authorization.k8s.io       
